import { describe, expect, it } from 'vitest';
import results from '@/data/sandboxEngineResults.json';
import { PRESET_TRACKS } from '@/data/presetTracks';
import { scoreSelection, selectionKey, getEngineRun, typicalSelection, type SandboxMode } from './sandboxMetrics';

/**
 * The sandbox displays real engine runs generated by the backend for every
 * possible selection, judged against all 120 shuffles of the same picks. These
 * tests check that data set is complete and sane, and re-derive some of its
 * numbers independently from the preset data.
 */

const MODES: SandboxMode[] = ['bu', 'df', 'ph', 'cm'];
const energy = new Map(PRESET_TRACKS.map((t) => [t.id, t.energy]));

function selections(mode: SandboxMode): string[][] {
  const ids = PRESET_TRACKS.filter((t) => t.category === mode).map((t) => t.id);
  const out: string[][] = [];
  const pick = (from: number, chosen: string[]) => {
    if (chosen.length === 5) return void out.push(chosen);
    for (let i = from; i < ids.length; i++) pick(i + 1, [...chosen, ids[i]]);
  };
  pick(0, []);
  return out;
}

function permutations<T>(items: T[]): T[][] {
  if (items.length <= 1) return [items];
  return items.flatMap((x, i) => permutations([...items.slice(0, i), ...items.slice(i + 1)]).map((r) => [x, ...r]));
}

const smoothnessOf = (e: number[]) =>
  Math.max(0, Math.min(100, Math.round(100 - (e.slice(1).reduce((a, x, i) => a + Math.abs(x - e[i]), 0) / (e.length - 1)) * 100)));

describe('sandbox engine results', () => {
  it('has a real engine run for every possible selection', () => {
    expect((results as { runs: number }).runs).toBe(1008);
    for (const mode of MODES) {
      const all = selections(mode);
      expect(all).toHaveLength(252);
      for (const ids of all) expect(getEngineRun(ids)).not.toBeNull();
    }
  });

  it('accounts for every chosen track: kept or set aside with a reason', () => {
    for (const mode of MODES) {
      for (const ids of selections(mode)) {
        const run = getEngineRun(ids)!;
        const seen = [...run.order.map((o) => o.id), ...run.excluded.map((x) => x.id)];
        expect(seen.sort()).toEqual([...ids].sort());
        expect(run.kept).toBe(run.order.length);
        run.excluded.forEach((x) => expect(x.reason.length).toBeGreaterThan(0));
      }
    }
  });

  it('keys selections regardless of the order they were clicked in', () => {
    expect(selectionKey(['u5', 'u1', 'u3', 'u2', 'u4'])).toBe('u1,u2,u3,u4,u5');
  });

  it("agrees with an independent smoothness calculation, on the engine's order and on the shuffles", () => {
    for (const mode of ['bu', 'cm'] as SandboxMode[]) {
      for (const ids of selections(mode).slice(0, 40)) {
        const run = getEngineRun(ids)!;
        const [value, shuffled] = run.bars.smoothness;
        expect(value).toBe(smoothnessOf(run.order.map((o) => energy.get(o.id)!)));
        const perms = permutations(ids).map((p) => smoothnessOf(p.map((id) => energy.get(id)!)));
        expect(shuffled).toBe(Math.round(perms.reduce((a, v) => a + v, 0) / perms.length));
      }
    }
  });

  it('gives every engine something it can fail', () => {
    // Guards against drifting back to easy preset data, where every check
    // passed on every selection and the cards could only ever look perfect.
    for (const mode of MODES) {
      const failures = selections(mode).filter((ids) =>
        Object.values(getEngineRun(ids)!.checks).some(([pass]) => pass === false)
      );
      expect(failures.length).toBeGreaterThan(0);
    }
  });
});

describe('scoreSelection', () => {
  it('returns nothing until five tracks are chosen', () => {
    expect(scoreSelection('bu', ['r1', 'r2'])).toBeNull();
  });

  it('produces in-range checks and bars for every selection in every mode', () => {
    for (const mode of MODES) {
      for (const ids of selections(mode)) {
        const s = scoreSelection(mode, ids)!;
        expect(s.checks.length).toBeGreaterThanOrEqual(2);
        expect(s.bars).toHaveLength(2);
        for (const c of s.checks) {
          expect([true, false, null]).toContain(c.pass);
          if (c.shuffled !== null) expect(c.shuffled).toBeGreaterThanOrEqual(0);
          if (c.shuffled !== null) expect(c.shuffled).toBeLessThanOrEqual(100);
        }
        for (const b of s.bars) {
          for (const v of [b.value, b.shuffled]) {
            if (v === null) continue;
            expect(Number.isFinite(v)).toBe(true);
            expect(v).toBeGreaterThanOrEqual(0);
            expect(v).toBeLessThanOrEqual(100);
          }
        }
        expect(s.passed).toBe(s.checks.filter((c) => c.pass === true).length);
        expect(s.applicable).toBe(s.checks.filter((c) => c.pass !== null).length);
        expect(s.summary.length).toBeGreaterThan(0);
      }
    }
  });

  it('matches Rise checks to the order it shows', () => {
    for (const ids of selections('bu')) {
      const s = scoreSelection('bu', ids)!;
      const e = s.tracks.map((t) => t.energy);
      expect(s.checks.find((c) => c.id === 'opens-calm')!.pass).toBe(e[0] === Math.min(...e));
      expect(s.checks.find((c) => c.id === 'ends-loudest')!.pass).toBe(e[e.length - 1] === Math.max(...e));
    }
  });

  it('only judges Unhinged anchoring when there is a swing', () => {
    for (const ids of selections('ph')) {
      const s = scoreSelection('ph', ids)!;
      const swing = s.checks.find((c) => c.id === 'swing')!.pass;
      const anchored = s.checks.find((c) => c.id === 'anchored')!.pass;
      expect(anchored === null).toBe(swing === false);
    }
  });

  it("names Frame's turn after the arc the engine chose", () => {
    for (const ids of selections('cm')) {
      const s = scoreSelection('cm', ids)!;
      const turn = s.checks.find((c) => c.id === 'turns')!.name;
      expect(turn).toBe(s.run.engine.actDirection === 'TANK_AND_SPIKE' ? 'Act II holds the valley' : 'Act II holds the peak');
    }
  });
});

describe('typicalSelection', () => {
  it('is deterministic and points at a real selection', () => {
    for (const mode of MODES) {
      expect(typicalSelection(mode)).toEqual(typicalSelection(mode));
      expect(getEngineRun(typicalSelection(mode))).not.toBeNull();
    }
  });
});

describe('comparison sentence', () => {
  it('reads as a sentence for every selection', () => {
    for (const mode of MODES) {
      for (const ids of selections(mode)) {
        const { comparison } = scoreSelection(mode, ids)!;
        expect(comparison).toMatch(/^(Beats a random order on (both measures|every measure|\d+ of \d+ measures)|No better than a random order on these measures)\.$|^$/);
      }
    }
  });
});
